# Generated by Django 4.2.27 on 2025-12-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(default='House', max_length=50),
        ),
    ]
